### ISSUE TITLE
Include reference link for preventDefault

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/jsdom-dom-challenge#1]
> As a user, I can leave comments on my gameplay, such as: "Wow, what a fun game this is."

To meet this requirement, students will need to make use of `preventDefault`, and I don't believe this is mentioned in earlier lessons/readings. 

https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault would do just fine

#staff

**Comment by sgharms** [comment]
https://github.com/learn-co-curriculum/jsdom-dom-challenge/commit/2ce1b3f629146dc3cb5a110f001e467b4f0b8bac

Fixes this issue. Also fixed it in taskLister which appears prior in the brick so that there's a more thorough introduction before this intentionally-abbreviated introduction
