### ISSUE TITLE
500 error for students on Learn.co

### ISSUE THREAD

**Issue by ChrstphGrnr** [learn-co-curriculum/jsdom-dom-challenge#11]
Just had a screenshare with a student who was attempting to open this lab's page on Learn.co and got a 500 error for the lab. 
I also attempted to click on the link for the lab and was unable to open it with the same 500 server error.

**Comment by Sdcrouse** [comment]
@ChrstphGrnr That appears to have been fixed. I am not seeing a 500 error when I open this lab.

**Comment by lizbur10** [comment]
Hey there! Given that this issue appears to have cleared, I'm going to close this 💙
