### ISSUE TITLE
Wrong line of code commented out

### ISSUE THREAD

**Issue by nlewis84** [learn-co-curriculum/jsdom-dom-challenge#18]
Per the instructions for this lab, line 43 of `index.html` should be commented out and line 42 should be uncommented. Otherwise, the lab will not do anything and may leave students not understanding why the lab is not functioning as intended. Students are instructed to switch the line of code that is commented out.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback. The materials have been updated to address the issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thanks for contributing to the Flatiron School curriculum! 💙
