### ISSUE TITLE
Horrible

### ISSUE THREAD

**Issue by jesspesale** [learn-co-curriculum/jsdom-dom-challenge#20]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

## What should be changed?

Suggest your change here. Let us know what section or line of the Readme needs
to be updated, and any proposed corrections. Include the line number(s) if
possible.

## Additional context

I have to say this lab is quite horrible and from where you are in the curriculum it's extremely impossible to finish on your own. I worked on it for over 3 days, with about 6+ tech coaches (and 10 mental break downs) and still was unable to finish it fully. If you are going to put such a difficult lab at least have a solution to lean on or tests to go off of because it was very stressful and a lot of tech coaches were even unable to help me. I am not one to give up easily but this lab for sure made me.

**Comment by ihollander** [comment]
Hi @jesspesale, thanks for your feedback and I'm sorry to hear that you had this experience with this lab. It is definitely a challenging exercise! Based on your feedback and feedback from other students, I've added a solution branch that has a video walkthrough along with one possible solution. The lesson was also moved to the 'Additional Practice' section in Canvas so it doesn't block students from progressing through the rest of the core material.
