### ISSUE TITLE
Lab, not a read me

### ISSUE THREAD

**Issue by eponsonby** [learn-co-curriculum/jsdom-dom-challenge#6]
The icon on this lab indicates that it's just a read me but it's actually a lab

**Comment by sgharms** [comment]
Hi, @eponsonby. There are no automated tests for this lesson, so Learn thinks that it's a readme. The icon is chosen dynamically based on the presence of automated tests. As far as I can tell, there aren't any tests in this repo. I'll close this accordingly. Let me know if there's something else afoot.
